version: 0.2
phases:
  pre_build:
    commands:
      - echo "Entered the pre-build phase"
  build:
    commands:
      - echo "Entered the build phase"
      - ./gradlew clean build
  post_build:
    commands:
      - echo "Enter the post-build phase"
artifacts:
  files:
    - build/libs/*
